name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Build image
        run: |
          gcloud builds submit \
            --tag "${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/request-service-api/request-service-api:${{ github.sha }}" \
            .

      - name: Deploy to Cloud Run
        run: |
          gcloud run services replace deployments/cloudrun.yaml \
            --region "${{ secrets.GCP_REGION }}" \
            --project "${{ secrets.GCP_PROJECT_ID }}"
