// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type VerificationEvent struct {
	ID                    pgtype.UUID        `json:"id"`
	VerificationRequestID pgtype.UUID        `json:"verification_request_id"`
	Source                string             `json:"source"`
	EventType             string             `json:"event_type"`
	Payload               []byte             `json:"payload"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type VerificationRequest struct {
	ID           pgtype.UUID        `json:"id"`
	BusinessRef  string             `json:"business_ref"`
	CandidateRef string             `json:"candidate_ref"`
	Provider     string             `json:"provider"`
	Status       string             `json:"status"`
	Verified     bool               `json:"verified"`
	ReasonCode   pgtype.Text        `json:"reason_code"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type VerificationSession struct {
	ID                    pgtype.UUID        `json:"id"`
	VerificationRequestID pgtype.UUID        `json:"verification_request_id"`
	Provider              string             `json:"provider"`
	ProviderSessionID     string             `json:"provider_session_id"`
	QrCodeUrl             pgtype.Text        `json:"qr_code_url"`
	DeepLink              pgtype.Text        `json:"deep_link"`
	OfferUrl              pgtype.Text        `json:"offer_url"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	RawCreateResponse     []byte             `json:"raw_create_response"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}
