// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verification_sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVerificationSession = `-- name: CreateVerificationSession :one
INSERT INTO verification_sessions (
    verification_request_id,
    provider,
    provider_session_id,
    qr_code_url,
    deep_link,
    offer_url,
    expires_at,
    raw_create_response
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, verification_request_id, provider, provider_session_id, qr_code_url, deep_link, offer_url, expires_at, raw_create_response, created_at
`

type CreateVerificationSessionParams struct {
	VerificationRequestID pgtype.UUID        `json:"verification_request_id"`
	Provider              string             `json:"provider"`
	ProviderSessionID     string             `json:"provider_session_id"`
	QrCodeUrl             pgtype.Text        `json:"qr_code_url"`
	DeepLink              pgtype.Text        `json:"deep_link"`
	OfferUrl              pgtype.Text        `json:"offer_url"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	RawCreateResponse     []byte             `json:"raw_create_response"`
}

func (q *Queries) CreateVerificationSession(ctx context.Context, arg CreateVerificationSessionParams) (VerificationSession, error) {
	row := q.db.QueryRow(ctx, createVerificationSession,
		arg.VerificationRequestID,
		arg.Provider,
		arg.ProviderSessionID,
		arg.QrCodeUrl,
		arg.DeepLink,
		arg.OfferUrl,
		arg.ExpiresAt,
		arg.RawCreateResponse,
	)
	var i VerificationSession
	err := row.Scan(
		&i.ID,
		&i.VerificationRequestID,
		&i.Provider,
		&i.ProviderSessionID,
		&i.QrCodeUrl,
		&i.DeepLink,
		&i.OfferUrl,
		&i.ExpiresAt,
		&i.RawCreateResponse,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestVerificationSessionByRequestID = `-- name: GetLatestVerificationSessionByRequestID :one
SELECT id, verification_request_id, provider, provider_session_id, qr_code_url, deep_link, offer_url, expires_at, raw_create_response, created_at
FROM verification_sessions
WHERE verification_request_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestVerificationSessionByRequestID(ctx context.Context, verificationRequestID pgtype.UUID) (VerificationSession, error) {
	row := q.db.QueryRow(ctx, getLatestVerificationSessionByRequestID, verificationRequestID)
	var i VerificationSession
	err := row.Scan(
		&i.ID,
		&i.VerificationRequestID,
		&i.Provider,
		&i.ProviderSessionID,
		&i.QrCodeUrl,
		&i.DeepLink,
		&i.OfferUrl,
		&i.ExpiresAt,
		&i.RawCreateResponse,
		&i.CreatedAt,
	)
	return i, err
}

const getVerificationSessionByProviderSessionID = `-- name: GetVerificationSessionByProviderSessionID :one
SELECT id, verification_request_id, provider, provider_session_id, qr_code_url, deep_link, offer_url, expires_at, raw_create_response, created_at
FROM verification_sessions
WHERE provider_session_id = $1
LIMIT 1
`

func (q *Queries) GetVerificationSessionByProviderSessionID(ctx context.Context, providerSessionID string) (VerificationSession, error) {
	row := q.db.QueryRow(ctx, getVerificationSessionByProviderSessionID, providerSessionID)
	var i VerificationSession
	err := row.Scan(
		&i.ID,
		&i.VerificationRequestID,
		&i.Provider,
		&i.ProviderSessionID,
		&i.QrCodeUrl,
		&i.DeepLink,
		&i.OfferUrl,
		&i.ExpiresAt,
		&i.RawCreateResponse,
		&i.CreatedAt,
	)
	return i, err
}
