// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verification_events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVerificationEvent = `-- name: CreateVerificationEvent :one
INSERT INTO verification_events (
    verification_request_id,
    source,
    event_type,
    payload
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, verification_request_id, source, event_type, payload, created_at
`

type CreateVerificationEventParams struct {
	VerificationRequestID pgtype.UUID `json:"verification_request_id"`
	Source                string      `json:"source"`
	EventType             string      `json:"event_type"`
	Payload               []byte      `json:"payload"`
}

func (q *Queries) CreateVerificationEvent(ctx context.Context, arg CreateVerificationEventParams) (VerificationEvent, error) {
	row := q.db.QueryRow(ctx, createVerificationEvent,
		arg.VerificationRequestID,
		arg.Source,
		arg.EventType,
		arg.Payload,
	)
	var i VerificationEvent
	err := row.Scan(
		&i.ID,
		&i.VerificationRequestID,
		&i.Source,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listVerificationEventsByRequestID = `-- name: ListVerificationEventsByRequestID :many
SELECT id, verification_request_id, source, event_type, payload, created_at
FROM verification_events
WHERE verification_request_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListVerificationEventsByRequestID(ctx context.Context, verificationRequestID pgtype.UUID) ([]VerificationEvent, error) {
	rows, err := q.db.Query(ctx, listVerificationEventsByRequestID, verificationRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VerificationEvent{}
	for rows.Next() {
		var i VerificationEvent
		if err := rows.Scan(
			&i.ID,
			&i.VerificationRequestID,
			&i.Source,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
