// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verification_requests.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVerificationRequest = `-- name: CreateVerificationRequest :one
INSERT INTO verification_requests (
    business_ref,
    candidate_ref,
    provider,
    status,
    verified,
    reason_code
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, business_ref, candidate_ref, provider, status, verified, reason_code, created_at, updated_at
`

type CreateVerificationRequestParams struct {
	BusinessRef  string      `json:"business_ref"`
	CandidateRef string      `json:"candidate_ref"`
	Provider     string      `json:"provider"`
	Status       string      `json:"status"`
	Verified     bool        `json:"verified"`
	ReasonCode   pgtype.Text `json:"reason_code"`
}

func (q *Queries) CreateVerificationRequest(ctx context.Context, arg CreateVerificationRequestParams) (VerificationRequest, error) {
	row := q.db.QueryRow(ctx, createVerificationRequest,
		arg.BusinessRef,
		arg.CandidateRef,
		arg.Provider,
		arg.Status,
		arg.Verified,
		arg.ReasonCode,
	)
	var i VerificationRequest
	err := row.Scan(
		&i.ID,
		&i.BusinessRef,
		&i.CandidateRef,
		&i.Provider,
		&i.Status,
		&i.Verified,
		&i.ReasonCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVerificationRequestByID = `-- name: GetVerificationRequestByID :one
SELECT id, business_ref, candidate_ref, provider, status, verified, reason_code, created_at, updated_at
FROM verification_requests
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetVerificationRequestByID(ctx context.Context, id pgtype.UUID) (VerificationRequest, error) {
	row := q.db.QueryRow(ctx, getVerificationRequestByID, id)
	var i VerificationRequest
	err := row.Scan(
		&i.ID,
		&i.BusinessRef,
		&i.CandidateRef,
		&i.Provider,
		&i.Status,
		&i.Verified,
		&i.ReasonCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVerificationRequestStatus = `-- name: UpdateVerificationRequestStatus :one
UPDATE verification_requests
SET
    status = $2,
    verified = $3,
    reason_code = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, business_ref, candidate_ref, provider, status, verified, reason_code, created_at, updated_at
`

type UpdateVerificationRequestStatusParams struct {
	ID         pgtype.UUID `json:"id"`
	Status     string      `json:"status"`
	Verified   bool        `json:"verified"`
	ReasonCode pgtype.Text `json:"reason_code"`
}

func (q *Queries) UpdateVerificationRequestStatus(ctx context.Context, arg UpdateVerificationRequestStatusParams) (VerificationRequest, error) {
	row := q.db.QueryRow(ctx, updateVerificationRequestStatus,
		arg.ID,
		arg.Status,
		arg.Verified,
		arg.ReasonCode,
	)
	var i VerificationRequest
	err := row.Scan(
		&i.ID,
		&i.BusinessRef,
		&i.CandidateRef,
		&i.Provider,
		&i.Status,
		&i.Verified,
		&i.ReasonCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
